// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBin-CoOIs5-llz_8z8WcKRtU15miiNk',
    appId: '1:577362452367:web:3fe32f3aed1606b4ee35fa',
    messagingSenderId: '577362452367',
    projectId: 'yavolvelo',
    authDomain: 'yavolvelo.firebaseapp.com',
    storageBucket: 'yavolvelo.appspot.com',
    measurementId: 'G-MGTBKSP7GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Hs2cCJQdXweQF7iQs7hoEcvgIWmbTeQ',
    appId: '1:577362452367:android:3259184c8144b6feee35fa',
    messagingSenderId: '577362452367',
    projectId: 'yavolvelo',
    storageBucket: 'yavolvelo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe94D0cVKKFe_pL18j5tFYSd_iGfhvDME',
    appId: '1:577362452367:ios:30bc76252e79265bee35fa',
    messagingSenderId: '577362452367',
    projectId: 'yavolvelo',
    storageBucket: 'yavolvelo.appspot.com',
    androidClientId: '577362452367-1gnom11tvrun8ffeh7c2cpdmtnn9niq1.apps.googleusercontent.com',
    iosClientId: '577362452367-8v9bs28a7r0c2jv7bfes1hugkasun8q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.acordame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe94D0cVKKFe_pL18j5tFYSd_iGfhvDME',
    appId: '1:577362452367:ios:30bc76252e79265bee35fa',
    messagingSenderId: '577362452367',
    projectId: 'yavolvelo',
    storageBucket: 'yavolvelo.appspot.com',
    androidClientId: '577362452367-1gnom11tvrun8ffeh7c2cpdmtnn9niq1.apps.googleusercontent.com',
    iosClientId: '577362452367-8v9bs28a7r0c2jv7bfes1hugkasun8q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.acordame',
  );
}
